from fastapi import FastAPI

app = FastAPI(
    title="AI-Built FastAPI Service",
    version="1.0.0",
    description="A minimal API generated and iterated by an AI coding agent running locally with Ollama.",
)

@app.get("/", tags=["default"])
def root():
    return {
        "message": "Hello! This FastAPI app was generated by an AI coding agent.",
        "try": ["/health", "/docs", "/openapi.json"],
    }

@app.get("/health", tags=["default"])
def health():
    return {"status": "healthy"}
